### ISSUE TITLE
create InstanceTemplate with no password

### ISSUE THREAD

**Issue by buddiewei** [terraform-providers/terraform-provider-jdcloud#3]
Creating of InstanceTemplate, must input password now!
But we hope to set password later！

**Comment by XiaohanLiang** [comment]
Hi,

Sorry for a late reply , you can now create instance template with keys by specifying `key_name`. At the same time , we have just updated our plugin to make it compatible to Terraform 0.12. You can now access to JDCloud-plugin in latest version of Terraform

BR,
XiaohanLiang
