### ISSUE TITLE
how to "Download Terraform-Jdcloud-Plugin"?

### ISSUE THREAD

**Issue by lidaobing** [terraform-providers/terraform-provider-jdcloud#6]
in `README.md`, there is "Download Terraform-Jdcloud-Plugin", but how to download it?

**Comment by XiaohanLiang** [comment]
Hi, Daobing

There are 3 different ways to access to our plugin, 

- [x] **Official version** : Official plugin will be downloaded by terraform automatically, once you have executed `terraform init` and a [jdcloud.tf file with provider "jdcloud" declaration](https://github.com/terraform-providers/terraform-provider-jdcloud/blob/master/example/main.tf#L3).

- [x] Developer version , **from binary** : Binary files will be generated automatically by TravisCI, which can be downloaded -> [here](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/releases)

- [X] Develop version, **from draft**: Alternatively you can clone the source code and compile yourself by using command `make build` , we would recommend people doing this only when they try to develop with this plugin 

BR,

XiaohanLiang
